# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Shuttle Management',
    'version': '16.24.0.1',
    'author': 'Estain Makaudze',
    'summary': 'Invoices & Payments',
    'sequence': -100,
    'description': """This is a module for shuttle management""",
    'category': 'Accounting/Accounting',
    'website': 'https://zimworx.odoo.com',
    'depends': ['contacts','mail','hr','hr_employee_inherit'],
    'data': [
        # security -- data -- views --reports
        'security/ir.model.access.csv',
        'views/main_menus.xml',
        'wizards/onboard_employee_for_shuttle.xml',
        'views/shuttle_email_template.xml',
        'wizards/shuttle_email_wizard.xml',
        'views/hr_employee_inheritance.xml',
        'views/hr_employee_driver_inheritance.xml',
        'views/shuttles_model.xml',
        'views/shuttle_routes_model.xml',
        'views/weekday_model.xml',
        'views/route_start_location_model.xml',
        'views/route_end_location_model.xml',
        'views/my_shuttle_template_controller.xml',
        'views/qr_code_scan.xml',
        'views/driver_login_template.xml',
        'views/onboard_my_shuttle_template.xml',
        'views/simple_onboard_scan_qr_code.xml',
        'views/my_shuttle_controller.xml',
        'views/onboard_scan_qr_code.xml',
        'reports/paper_formats.xml',
        'reports/qr_code_report.xml',
        'reports/reports_options.xml',
        'wizards/upload_old_qr_codes.xml',
        'wizards/upload_external_shuttle_schedules.xml',
        'views/billing_tariff.xml',
        # 'views/default_views.xml',
        # 'report/default_report.xml',
    ],
    'demo': [],
    'qweb': [],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'auto_install': False,
}